# This is a basic workflow to help you get started with Actions

name: Firebase Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{ secrets. REACT_APP_API_KEY }}
      REACT_APP_APP_ID:  ${{ secrets. REACT_APP_APP_ID }}
      REACT_APP_AUTH_DOMAIN: ${{ secrets. REACT_APP_AUTH_DOMAIN }}
      REACT_APP_DATABASE_URL:  ${{ secrets. REACT_APP_DATABASE_URL }}
      REACT_APP_LOCAL_BACKEND_URL:  ${{ secrets. REACT_APP_LOCAL_BACKEND_URL }}
      REACT_APP_MEASUREMENT_ID: ${{ secrets. REACT_APP_MEASUREMENT_ID }}
      REACT_APP_MESSAGING_SENDERID:  ${{ secrets. REACT_APP_MESSAGING_SENDERID }}
      REACT_APP_PROD_BACKEND_URL:  ${{ secrets. REACT_APP_PROD_BACKEND_URL }}
      REACT_APP_PROJECT_ID: ${{ secrets. REACT_APP_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets. REACT_APP_STORAGE_BUCKET }}
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    # Runs a single command using the runners shell
    - name: client Build
      run: |
         cd client
         npm install
         npm run build

    # Runs a set of commands using the runners shell
    - name: functions Build
      run: |
        cd functions
        npm install
         
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
