name: CI

on: 
  issues: [opened,edited]
  pull_request: 
    branches: [master]
    

jobs:
  all-tests:
    name: All test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
      working-directory: ./functions
    - run: npm test
      working-directory: ./functions
      env:
        CI: true
